spring.datasource.url=jdbc:postgresql://localhost:5432/Warehouses
spring.datasource.username=postgres
spring.datasource.password=mango

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true