spring.datasource.url=jdbc:postgresql://localhost:5432/Anonbook
spring.datasource.username=postgres
spring.datasource.password=mango

spring.jpa.hibernate.ddl-auto=validate

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration